services:
    python-pddl:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../:/workspace
        environment:
            - DOMAIN
            - PROBLEM
            - PLANNER
            - HEURISTIC
